### Obtener todos los burocratas
GET http://localhost:3000/api/Burocratas


### Obtener un burocrata por id
GET http://localhost:3000/api/Burocratas/5


### Crear un nuevo burocrata
#   @name createBurocrata
POST http://localhost:3000/api/Burocratas
Content-Type: application/json

{
  "nombreBuro": "Tomás",
  "aliasBuro": "elGordo",
  "origenBuro": "miCasa",
  "telefono": "12345",
  "mailBuro": "hola"
}
### ID
@id = {{createBurocrata.response.body.data.id}}


###Actualiza el burocrata
PUT http://localhost:3000/api/Burocratas/5
Content-Type: application/json

{
       "nombreBuro":"Tomas",
       "aliasBuro":"elGordo",
       "origenBuro":"miCasa",
       "telefono":"12345",
       "mailBuro:":"tommyszalich@gmail.com"
}


### Actualizar solo algunos datos
PATCH http://localhost:3000/api/Burocratas/5
Content-Type: application/json

{
       "nombreBuro":"Tomassssss",
       "aliasBuro":"elGordoooooo",
       "origenBuro":"miCasaaaaaa",
       "telefono":"1234555555",
       "mailBuro:":"tommyszalichhh@gmail.com"
}


### Eliminar un burocrata
DELETE http://localhost:3000/api/Burocratas/3
