###Obtener una multa
GET http://localhost:3000/api/Multas



### Obtener una multa por id
GET http://localhost:3000/api/Multas/3

### Crear una nueva multa
#  @name createMulta
POST http://localhost:3000/api/Multas
Content-Type: application/json

{
  "motivoMulta":"pajaaaaaaaaaaaaaaaaaaaa",
  "montoMulta":69,
  "lugarDePago":"tu casaaaaaaaaaaaaaaaaaaaa",
  "fechaEmision":"acaaaaaaaaaaaaaaaaa",
  "estado":"muerto",
  "fechaVencimiento":"aaaaaaaaaaaaaaaaaaa"
}
###ID
@id = {{createMulta.response.body.data.id}}

###Actualiza la multa

PUT http://localhost:3000/api/Multas/3
Content-Type: application/json

{
  "motivoMulta":"pajaaaaaaa",
  "montoMulta":6969,
  "LugarDePago":"tu casaaaaaa",
  "fechaEmision":"acaaaaaa",
  "estado":"muertaaaaao",
  "fechaVencimiento":"aaaaaaaaaa"
}


### Actualizar solo algunos datos
PATCH http://localhost:3000/api/Multas/3
Content-Type: application/json

{
  "motivoMulta":"paja",
  "montoMulta" : "696969",
  "LugarDePago":"tu casa",
  "fechaEmision":"aca",
  "estado":"muerto",
  "fechaVencimiento":"aaaaa"
}


### Eliminar una multa
DELETE http://localhost:3000/api/Multas/3